[versions]
androidApplication = "8.7.3"
androidXTest = "1.6.1"
androidXTestRunner = "1.6.2"
androidXTestUiAutomator = "2.3.0"
androidXArchCore = "2.2.0"
androidXCoreRemoteViews = "1.1.0"
andromedaVersion = "11.3.0"
cameraxVersion = "1.4.0"
coreKtx = "1.15.0"
appcompat = "1.7.0"
constraintlayout = "2.2.0"
desugar_jdk_libs = "2.1.3"
flexbox = "3.0.0"
fragment = "1.8.5"
gridlayout = "1.0.0"
hiltAndroidCompilerVersion = "2.49"
hiltAndroidVersion = "2.49"
hiltCompilerVersion = "1.2.0"
hiltWorkVersion = "1.2.0"
junitJupiter = "5.11.3"
junitPlatformRunner = "1.11.3"
junitVersion = "1.2.1"
junit = "4.13.2"
kotlinAndroidVersion = "2.0.0"
kotlinxCoroutinesAndroid = "1.8.0"
ksp = "2.0.0-1.0.21"
legacySupportV4 = "1.0.0"
navVersion = "2.8.4"
lifecycleVersion = "2.8.7"
material = "1.10.0"
luna = "0.3.5"
mockitoKotlin = "5.1.0"
roomVersion = "2.6.1"
sol = "9.12.1"
subsamplingScaleImageView = "3.11.9"
workRuntimeKtx = "2.10.0"
preferenceKtx = "1.2.1"

[libraries]
androidx-test-core = { module = "androidx.test:core", version.ref = "androidXTest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidXTestRunner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidXTest" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidXTestUiAutomator" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "fragment" }
androidx-fragment-testing-manifest = { module = "androidx.fragment:fragment-testing-manifest", version.ref = "fragment" }
androidx-test-arch-core = { module = "androidx.arch.core:core-testing", version.ref = "androidXArchCore" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompilerVersion" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWorkVersion" }
androidx-core-remoteviews = { module = "androidx.core:core-remoteviews", version.ref = "androidXCoreRemoteViews" }
andromeda-battery = { module = "com.github.kylecorry31.andromeda:battery", version.ref = "andromedaVersion" }
andromeda-buzz = { module = "com.github.kylecorry31.andromeda:buzz", version.ref = "andromedaVersion" }
andromeda-clipboard = { module = "com.github.kylecorry31.andromeda:clipboard", version.ref = "andromedaVersion" }
andromeda-exceptions = { module = "com.github.kylecorry31.andromeda:exceptions", version.ref = "andromedaVersion" }
andromeda-compression = { module = "com.github.kylecorry31.andromeda:compression", version.ref = "andromedaVersion" }
andromeda-markdown = { module = "com.github.kylecorry31.andromeda:markdown", version.ref = "andromedaVersion" }
andromeda-list = { module = "com.github.kylecorry31.andromeda:list", version.ref = "andromedaVersion" }
andromeda-alerts = { module = "com.github.kylecorry31.andromeda:alerts", version.ref = "andromedaVersion" }
andromeda-notify = { module = "com.github.kylecorry31.andromeda:notify", version.ref = "andromedaVersion" }
andromeda-files = { module = "com.github.kylecorry31.andromeda:files", version.ref = "andromedaVersion" }
andromeda-canvas = { module = "com.github.kylecorry31.andromeda:canvas", version.ref = "andromedaVersion" }
andromeda-core = { module = "com.github.kylecorry31.andromeda:core", version.ref = "andromedaVersion" }
andromeda-pdf = { module = "com.github.kylecorry31.andromeda:pdf", version.ref = "andromedaVersion" }
andromeda-permissions = { module = "com.github.kylecorry31.andromeda:permissions", version.ref = "andromedaVersion" }
andromeda-pickers = { module = "com.github.kylecorry31.andromeda:pickers", version.ref = "andromedaVersion" }
andromeda-preferences = { module = "com.github.kylecorry31.andromeda:preferences", version.ref = "andromedaVersion" }
andromeda-print = { module = "com.github.kylecorry31.andromeda:print", version.ref = "andromedaVersion" }
andromeda-qr = { module = "com.github.kylecorry31.andromeda:qr", version.ref = "andromedaVersion" }
andromeda-signal = { module = "com.github.kylecorry31.andromeda:signal", version.ref = "andromedaVersion" }
andromeda-sense = { module = "com.github.kylecorry31.andromeda:sense", version.ref = "andromedaVersion" }
andromeda-sound = { module = "com.github.kylecorry31.andromeda:sound", version.ref = "andromedaVersion" }
andromeda-gpx = { module = "com.github.kylecorry31.andromeda:gpx", version.ref = "andromedaVersion" }
andromeda-camera = { module = "com.github.kylecorry31.andromeda:camera", version.ref = "andromedaVersion" }
andromeda-background = { module = "com.github.kylecorry31.andromeda:background", version.ref = "andromedaVersion" }
andromeda-csv = { module = "com.github.kylecorry31.andromeda:csv", version.ref = "andromedaVersion" }
andromeda-xml = { module = "com.github.kylecorry31.andromeda:xml", version.ref = "andromedaVersion" }
andromeda-forms = { module = "com.github.kylecorry31.andromeda:forms", version.ref = "andromedaVersion" }
andromeda-fragments = { module = "com.github.kylecorry31.andromeda:fragments", version.ref = "andromedaVersion" }
andromeda-torch = { module = "com.github.kylecorry31.andromeda:torch", version.ref = "andromedaVersion" }
andromeda-views = { module = "com.github.kylecorry31.andromeda:views", version.ref = "andromedaVersion" }
andromeda-widgets = { module = "com.github.kylecorry31.andromeda:widgets", version.ref = "andromedaVersion" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraxVersion" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraxVersion" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraxVersion" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompilerVersion" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidVersion" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitJupiter" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiter" }
junit-platform-runner = { module = "org.junit.platform:junit-platform-runner", version.ref = "junitPlatformRunner" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleVersion" }
lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycleVersion" }
luna = { module = "com.github.kylecorry31:luna", version.ref = "luna" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navVersion" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navVersion" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
sol = { module = "com.github.kylecorry31:sol", version.ref = "sol" }
subsampling-scale-image-view = { module = "com.github.kylecorry31:subsampling-scale-image-view", version.ref = "subsamplingScaleImageView" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroidVersion" }
work-testing = { module = "androidx.work:work-testing", version.ref = "workRuntimeKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidApplication" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroidVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroidVersion" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }